using GBX.NET; using GBX.NET.Engines.GameData; using GBX.NET.Engines.Meta; using GBX.NET.Engines.MetaNotPersistent; using GBX.NET.Engines.Plug; using GBX.NET.Engines.MwFoundations; using TM_Item_Studio.Models;
var passed=0;
Check("inspect shared",()=>{var v=Visual();var s=Solid(v);var p=new CPlugPrefab{Ents=new[]{new CPlugPrefab.EntRef{Model=s},new CPlugPrefab.EntRef{Model=s}}};var d=Document(p);var paths=ItemScene.Build(d.Node,0).Handles.Visuals.Where(x=>ReferenceEquals(x.Source,v)).Select(x=>x.Path).ToArray();var scope=ItemMaterialEdits.InspectUv0(d,0,paths[0]);Req(scope.VertexCount==3&&scope.OccurrencePaths.Count==2,"scope");});
Check("apply refuses atomically",()=>{var v=Visual();var d=Document(Solid(v));var path=ItemScene.Build(d.Node,0).Handles.Visuals.Single().Path;var b=Save(d);Throws(()=>ItemMaterialEdits.ApplyUv0(d,0,path,new(2,3,90,1,-1)),b,d);});
Check("invalid and opaque refuse",()=>{var v=Visual();var d=Document(Solid(v));var path=ItemScene.Build(d.Node,0).Handles.Visuals.Single().Path;var b=Save(d);Throws(()=>ItemMaterialEdits.ApplyUv0(d,0,path,new(float.NaN)),b,d);v.TexCoords=new[]{v.TexCoords[1]};b=Save(d);Throws(()=>ItemMaterialEdits.ApplyUv0(d,0,path,new()),b,d);var sv=StreamVisual();d=Document(Solid(sv));path=ItemScene.Build(d.Node,0).Handles.Visuals.Single().Path;b=Save(d);Throws(()=>ItemMaterialEdits.ApplyUv0(d,0,path,new()),b,d);});
Check("hidden variants included",()=>{var v=Visual();var list=new NPlugItem_SVariantList{Variants=new[]{new NPlugItem_SVariant{EntityModel=Solid(v)},new NPlugItem_SVariant{EntityModel=new CPlugSolid2Model(),HiddenInManualCycle=true}}};var d=Document(list);var b=Save(d);Throws(()=>ItemMaterialEdits.InspectUv0(d,0,"doc:0/variant:0/root/entityModel/variant:0/entityModel/visual:0"),b,d);});
Console.WriteLine($"{passed} passed");return 0;
void Check(string n,Action a){a();passed++;Console.WriteLine("PASS: "+n);} static void Req(bool x,string m){if(!x)throw new Exception(m);} static void Throws(Action a,byte[] b,Gbx<CGameItemModel>d){try{a();throw new Exception("expected refusal");}catch(NotSupportedException){Req(b.SequenceEqual(Save(d)),"mutated");}catch(ArgumentException){Req(b.SequenceEqual(Save(d)),"mutated");}}
static Gbx<CGameItemModel> Document(CMwNod r){var i=new CGameItemModel{EntityModel=r,ItemType=CGameItemModel.EItemType.Ornament};i.CreateChunk<CGameItemModel.HeaderChunk2E002000>();i.CreateChunk<CGameItemModel.Chunk2E002019>().Version=15;return new(i){BodyCompression=GbxCompression.Uncompressed};} static byte[] Save(Gbx<CGameItemModel>d){using var s=new MemoryStream();d.Save(s);return s.ToArray();}
static CPlugSolid2Model Solid(CPlugVisual v)=>new(){Visuals=new[]{v},CustomMaterials=new[]{new CPlugSolid2Model.Material()},ShadedGeoms=new[]{new CPlugSolid2Model.ShadedGeom{VisualIndex=0,MaterialIndex=0,LodMask=1}}};
static CPlugVisualIndexedTriangles Visual(){var v=new CPlugVisualIndexedTriangles{Vertices=new[]{new CPlugVisual3D.Vertex(new Vec3(),new Vec3(0,0,1),null,null,null,null,null),new CPlugVisual3D.Vertex(new Vec3(1,0,0),new Vec3(0,0,1),null,null,null,null,null),new CPlugVisual3D.Vertex(new Vec3(0,1,0),new Vec3(0,0,1),null,null,null,null,null)},IndexBuffer=new CPlugIndexBuffer{Indices=new[]{0,1,2}},TexCoords=new[]{new CPlugVisual.TexCoordSet{TexCoords=new[]{new CPlugVisual.TexCoord(new Vec2(),null,null),new CPlugVisual.TexCoord(new Vec2(.5f,0),null,null),new CPlugVisual.TexCoord(new Vec2(0,.5f),null,null)}},new CPlugVisual.TexCoordSet{TexCoords=new[]{new CPlugVisual.TexCoord(new Vec2(.7f,.8f),null,null),new CPlugVisual.TexCoord(new Vec2(.1f,.2f),null,null),new CPlugVisual.TexCoord(new Vec2(.3f,.4f),null,null)}}}};v.CreateChunk<CPlugVisual.Chunk09006008>();v.CreateChunk<CPlugVisual3D.Chunk0902C003>();v.CreateChunk<CPlugVisualIndexed.Chunk0906A000>();return v;}
static CPlugVisualIndexedTriangles StreamVisual(){var s=new CPlugVertexStream{Positions=new[]{new Vec3(),new Vec3(1,0,0),new Vec3(0,1,0)},UVs=new(){[0]=new[]{new Vec2(),new Vec2(.5f,0),new Vec2(0,.5f)}}};var v=new CPlugVisualIndexedTriangles{VertexStreams=new(){s},IndexBuffer=new CPlugIndexBuffer{Indices=new[]{0,1,2}}};v.CreateChunk<CPlugVisual.Chunk0900600A>();v.CreateChunk<CPlugVisualIndexed.Chunk0906A001>();s.CreateChunk<CPlugVertexStream.Chunk09056000>();return v;}
